config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  
  resources :tasks


get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

get 'signup', to: 'users#new'
resources :users, only: [:index, :show, :create]

resources :tasks, only: [:create, :edit, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

include SessionsHelper

private

def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
end

def count(user)
  @count_tasks = user.tasks.count
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def index
    if logged_in?
        @tasks = current_user.tasks.order(id: :desc).page(params[:page])
    end
  end

  def show
     
  end

  def new
      @task = Task.new
  end

  def create
      @task = current_user.tasks.build(task_params)
      
      if @task.save
          flash[:success] = 'タスクを追加しました'
          redirect_to @task
      else
          flash.now[:danger] = 'タスクの追加に失敗しました'
          render :new
      end
  end

  def edit
       
  end

  def update
      
      if @task.update(task_params)
          flash[:success] = 'タスクを更新しました'
          redirect_to @task
      else
          flash.now[:danger] = 'タスクの更新に失敗しました'
          render :edit
      end
  end

  def destroy
      @task.destroy
      
      flash[:success] = 'タスクを削除しました'
      redirect_to tasks_url
  end
  
  private
  
  def set_task
   @task = Task.find(params[:id])
  end
  
  #Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :require_user_logged_in, only: [:index, :show]

  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <u>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<a href="/">Tasklist</a>

<div id="navbarSupportedContent">
      <ul>
        <% if logged_in? %>
          <li><%= link_to 'Users', users_path %></li>
          <li>
            <a href="#" data-toggle="dropdown"><%= current_user.name %></a>
            <ul>
              <li><%= link_to 'My profile', user_path(current_user) %></li>
              <li><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Signup', signup_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <%=  render 'layouts/flash_messages' %>
    
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
    <%= form_with(model: task, local: true) do |f| %>
    
    <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
        <%= f.label :content,'タスク名' %>
        <%= f.text_field :content %>
        <%= f.label :status,'ステータス' %>
        <%= f.text_field :status %>
        <%= f.submit '追加' %>
    <% end %>
    
    <p>ログイン完了ユーザ: <%= current_user.name %></p>

app/views/tasks/_task.html.erb
<% tasks.each do |micropost| %>
    <li>
      <img src="<%= gravatar_url(micropost.user, { size: 50 }) %>" alt="">
      <div>
        <div>
          <%= link_to task.user.name, user_path(task.user) %> <span class="text-muted">posted at <%= task.created_at %></span>
        </div>
        <div>
          <p><%= task.content %></p>
        </div>
        <div>
          <% if current_user == task.user %>
            <%= link_to "Delete", task, method: :delete, data: { confirm: "You sure?" } %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate tasks %>
</ul>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %>のタスクを編集</h1>
<%= render 'form', task: @task %>
<%= link_to 'タスク一覧',tasks_path %>

app/views/tasks/index.html.erb
<h1>タスクの一覧を表示</h1>

<ul>
    <% @tasks.each do |task| %>
    <li>[user=<%= task.user_id %>]  タスク番号:<%= link_to task.id, task_path(task) %> 「 <%= task.content %> 」 <%= task.status %></li>
    <% end %>
</ul>


<%= link_to 'タスクを追加', new_task_path %>

<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
<% else %>
      <h1>Welcome to the Tasklist</h1>
      <%= link_to 'Sign up now!', signup_path %>

<% end %>

app/views/tasks/new.html.erb
<h1>タスクを新規追加</h1>
<%= render 'form', task: @task %>
<%= link_to 'タスク一覧',tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %>の詳細内容</h1>
<p>タスク名 : <%= @task.content %></p>
<p>ステータス : <%= @task.status %></p>

<%= link_to 'タスク一覧',tasks_path %>
<%= link_to 'タスクを編集', edit_task_path(@task) %>
<%= link_to 'タスクを削除', @task, method: :delete, data: {confirm: '本当に削除してよろしいですか？'} %>

app/views/users/_users.html.erb
<% if users.any? %>
    <ul>
        <% users.each do |user| %>
        <li>
            <img src="<%= gravatar_url(user, { size: 50 }) %>" alt=""></img>
            <div>
                <div><%= user.name %></div>
                <div>
                    <p><%= link_to 'View profile', user_path(user) %></p>
                </div>
            </div>
        </li>
        <% end %>
    </ul>
    <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

    <div>

        <div>
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name %>
         </div>

        <div>
            <%= f.label :email, 'Email' %>
            <%= f.email_field :email %>
        </div>

        <div>
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password %>
        </div>

        <div>
            <%= f.label :password_confirmation, 'Confirmation' %>
            <%= f.password_field :password_confirmation %>
        </div>

        <%= f.submit 'Sign up' %>
    </div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<div>
  <h3><%= @user.name %></h3>
</div>
<div>
  <img src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
</div>



<ul class="nav nav-tabs nav-justified mb-3">
  <li class="nav-item"><a href="/" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">tasklist<%= @count_tasklists %></a></li>
  <li class="nav-item"><a href="#" class="nav-link">Followings</a></li>
  <li class="nav-item"><a href="#" class="nav-link">Followers</a></li>
</ul>